<?php

return [
    ['name' => 'Abso', 'representative_name' => 'Damian', 'representative_email' => 'bobby@absoheating.co.za', 'representative_contact_1' => '0825559102', 'representative_contact_2' => '0215527303'],
    ['name' => 'ABR', 'representative_name' => 'Harold', 'representative_email' => 'info@abrengineering.co.za', 'representative_contact_1' => '0834460675', 'representative_contact_2' => ''],
    ['name' => 'ABR', 'representative_name' => 'Gerard', 'representative_email' => 'info@abrengineering.co.za', 'representative_contact_1' => '0744646370', 'representative_contact_2' => ''],
    ['name' => 'AC Pneumatics', 'representative_name' => 'Adrian', 'representative_email' => 'acpneumatics@gmail.com', 'representative_contact_1' => '0217629944', 'representative_contact_2' => '0834449856'],
    ['name' => 'Allbro', 'representative_name' => 'Faizel', 'representative_email' => 'faizel@allbro.com', 'representative_contact_1' => '0823208372', 'representative_contact_2' => '0118948341'],
    ['name' => 'Aylesbury', 'representative_name' => 'Nishal', 'representative_email' => 'nishalramdeo1976@gmail.com ', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Barkev', 'representative_name' => 'Carmen', 'representative_email' => 'carmen@barkev.co.za', 'representative_contact_1' => '0215583454', 'representative_contact_2' => ''],
    ['name' => 'Barkev', 'representative_name' => 'Gavin', 'representative_email' => 'cptnorth@barkev.co.za', 'representative_contact_1' => '0215583454', 'representative_contact_2' => '0832699508'],
    ['name' => 'Belting Edge', 'representative_name' => 'Tayla', 'representative_email' => 'sales@beltingedge.co.za', 'representative_contact_1' => '0682176060', 'representative_contact_2' => '0215570129'],
    ['name' => 'BMG Componentry', 'representative_name' => 'Hilton', 'representative_email' => 'hiltonl@bmgworld.net', 'representative_contact_1' => '0214924090', 'representative_contact_2' => ''],
    ['name' => 'BMG Componentry', 'representative_name' => 'Trevor', 'representative_email' => 'trevoro@bmgworld.net', 'representative_contact_1' => '0716711837', 'representative_contact_2' => '0219451850'],
    ['name' => 'BMG Belts', 'representative_name' => 'Neil', 'representative_email' => 'neils@bmgworld.net', 'representative_contact_1' => '0824955166', 'representative_contact_2' => '0214933250'],
    ['name' => 'BMG Gearboxes', 'representative_name' => 'Carlo', 'representative_email' => 'carlol@bmgworld.net', 'representative_contact_1' => '0824675756', 'representative_contact_2' => '0214963250'],
    ['name' => 'Bonfigioli', 'representative_name' => 'Rodney', 'representative_email' => 'Rodney.Waldeck@bonfiglioli.com', 'representative_contact_1' => '0823376864', 'representative_contact_2' => '0215512660'],
    ['name' => 'Cape Town Castors', 'representative_name' => 'Morne', 'representative_email' => 'morne@castorscapetown.com', 'representative_contact_1' => '0826930000', 'representative_contact_2' => ''],
    ['name' => 'CBMS', 'representative_name' => 'Chad', 'representative_email' => 'chad@salescbms.co.za', 'representative_contact_1' => '0662091718', 'representative_contact_2' => ''],
    ['name' => 'CBMS', 'representative_name' => 'Karynn', 'representative_email' => 'karynn@salescbms.co.za', 'representative_contact_1' => '0639817060', 'representative_contact_2' => ''],
    ['name' => 'CIM', 'representative_name' => 'Emily', 'representative_email' => 'sales@cimautomation.co.za', 'representative_contact_1' => '0215311410', 'representative_contact_2' => ''],
    ['name' => 'CJ & Son', 'representative_name' => 'Brumilda', 'representative_email' => 'cjandsoneng@yahoo.com', 'representative_contact_1' => '0714362515', 'representative_contact_2' => ''],
    ['name' => 'CJ & Son', 'representative_name' => 'Janess', 'representative_email' => 'cjandsoneng@yahoo.com', 'representative_contact_1' => '0743332077', 'representative_contact_2' => ''],
    ['name' => 'Coastal Engineering', 'representative_name' => 'Trudie', 'representative_email' => 'trudiep@coastalengineering.co.za', 'representative_contact_1' => '0215526063', 'representative_contact_2' => ''],
    ['name' => 'CTE', 'representative_name' => 'Elric', 'representative_email' => 'elric@cteng.co.za', 'representative_contact_1' => '0824415207', 'representative_contact_2' => '0215114983'],
    ['name' => 'DC Wort', 'representative_name' => 'Sharon', 'representative_email' => 'sharon@dcwort.co.za', 'representative_contact_1' => '0119650015', 'representative_contact_2' => ''],
    ['name' => 'Design your Sign', 'representative_name' => 'Monica', 'representative_email' => 'monica@designyoursign.co.za', 'representative_contact_1' => '0215952259', 'representative_contact_2' => ''],
    ['name' => 'Design your Sign', 'representative_name' => 'George', 'representative_email' => 'george@designyoursign.co.za', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Deurou', 'representative_name' => 'Willem', 'representative_email' => 'willem@deurou.co.za', 'representative_contact_1' => '0218544955', 'representative_contact_2' => ''],
    ['name' => 'Electromechinica', 'representative_name' => 'Brandon', 'representative_email' => 'rubenb@em.co.za', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Elliott & Small', 'representative_name' => 'Bryce', 'representative_email' => 'sales2@elliottsmall.co.za', 'representative_contact_1' => '0119471711', 'representative_contact_2' => ''],
    ['name' => 'Energi Solutions', 'representative_name' => 'Heinrich', 'representative_email' => 'Heinrich.Dryling@energisolutionsafrica.com', 'representative_contact_1' => '0217628995', 'representative_contact_2' => ''],
    ['name' => 'Festo', 'representative_name' => 'Pierre', 'representative_email' => 'pierre.vanniekerk@festo.com', 'representative_contact_1' => '0836490144', 'representative_contact_2' => ''],
    ['name' => 'Gartech', 'representative_name' => 'Chris', 'representative_email' => 'chris@gartech.co.za', 'representative_contact_1' => '0834532331', 'representative_contact_2' => '0215343388'],
    ['name' => 'Gartech', 'representative_name' => 'Brandon', 'representative_email' => 'brandon@gartech.co.za ', 'representative_contact_1' => '0215343388', 'representative_contact_2' => ''],
    ['name' => 'Gelmar', 'representative_name' => 'Siwe', 'representative_email' => 'Willowbridge@gelmar.co.za', 'representative_contact_1' => '0212002460', 'representative_contact_2' => ''],
    ['name' => 'Gripper', 'representative_name' => 'Aminah', 'representative_email' => 'Aminah@gripper.co.za', 'representative_contact_1' => '0214477203', 'representative_contact_2' => ''],
    ['name' => 'HG Molenaar', 'representative_name' => 'Hendrik', 'representative_email' => 'hendrikc@hgmolenaar.com', 'representative_contact_1' => '0713553670', 'representative_contact_2' => '0218682210'],
    ['name' => 'HG Molenaar', 'representative_name' => 'Megan', 'representative_email' => 'Chrismyb@hgmolenaar.com', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Hose Solutions', 'representative_name' => 'Ally', 'representative_email' => 'ally@hosesol.co.za', 'representative_contact_1' => '0845118685', 'representative_contact_2' => ''],
    ['name' => 'Hose Solutions', 'representative_name' => 'Raschelle', 'representative_email' => 'reception@hosesol.co.za', 'representative_contact_1' => '0219431941', 'representative_contact_2' => ''],
    ['name' => 'Igus E-Chain', 'representative_name' => 'Edwin', 'representative_email' => 'evanniekerk@igus.net', 'representative_contact_1' => '0726506142', 'representative_contact_2' => '0113121848'],
    ['name' => 'Igus Spindles', 'representative_name' => 'Dennis', 'representative_email' => 'dmabena@igus.net', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Macsteel', 'representative_name' => 'Shamilla', 'representative_email' => 'Shamilla.delong@macsteel.co.za', 'representative_contact_1' => '021 950 5500', 'representative_contact_2' => ''],
    ['name' => 'Maedler', 'representative_name' => 'Marcel', 'representative_email' => 'marcel.albert@maedler.de', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Maedler', 'representative_name' => 'Corina', 'representative_email' => 'corina.royla@maedler.de', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'McNaughtans', 'representative_name' => 'Pieter', 'representative_email' => 'pieter@mcnaughtan.co.za', 'representative_contact_1' => '0659773142', 'representative_contact_2' => '0219390021'],
    ['name' => 'Mechanical Concepts', 'representative_name' => 'Kevin', 'representative_email' => 'kevin@mechanicalconcepts.co.za', 'representative_contact_1' => '0829255895', 'representative_contact_2' => ''],
    ['name' => 'Modular', 'representative_name' => 'Malcolm', 'representative_email' => 'malcolm@moduasm.co.za', 'representative_contact_1' => '0681518815', 'representative_contact_2' => '0414512712'],
    ['name' => 'Next Level Tech', 'representative_name' => 'Charles', 'representative_email' => 'website@nxtleveltech.co.za', 'representative_contact_1' => '0219058044', 'representative_contact_2' => ''],
    ['name' => 'Norelem', 'representative_name' => 'Joel', 'representative_email' => 'joel.boden@norelem.se', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Norelem', 'representative_name' => 'Manuela', 'representative_email' => 'manuela.korb@norelem.de', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Powermite', 'representative_name' => 'David', 'representative_email' => 'david@powermite.co.za', 'representative_contact_1' => '0219511505', 'representative_contact_2' => ''],
    ['name' => 'Principal Power', 'representative_name' => 'Jharred', 'representative_email' => 'jharred.n@principalpower.co.za', 'representative_contact_1' => '0215519972', 'representative_contact_2' => ''],
    ['name' => 'Progress Precision Engineering', 'representative_name' => 'Marco', 'representative_email' => 'marco@ppeng.co.za', 'representative_contact_1' => '0215519909', 'representative_contact_2' => ''],
    ['name' => 'PYM ', 'representative_name' => 'Pierre-Yves', 'representative_email' => 'maurelpy@gmail.com', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Rittal', 'representative_name' => 'Melissa', 'representative_email' => 'internalsales3@rittal.co.za', 'representative_contact_1' => '0116098294', 'representative_contact_2' => ''],
    ['name' => 'Rittal', 'representative_name' => 'Samantha', 'representative_email' => 'joseph.s@rittal.co.za', 'representative_contact_1' => '0718524176', 'representative_contact_2' => '0116098294'],
    ['name' => 'Roemers', 'representative_name' => 'Natasha', 'representative_email' => 'sales@roemers.co.za', 'representative_contact_1' => '0214472371', 'representative_contact_2' => ''],
    ['name' => 'Roemers', 'representative_name' => 'Shannay', 'representative_email' => 'info@roemers.co.za', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Rora', 'representative_name' => 'Eugene', 'representative_email' => 'rora@ncsgroup.co.za', 'representative_contact_1' => '0832263079', 'representative_contact_2' => ''],
    ['name' => 'RPM Componentry', 'representative_name' => 'ivor', 'representative_email' => 'ivor@rpm.co.za', 'representative_contact_1' => '0835650342', 'representative_contact_2' => ''],
    ['name' => 'RPM Rollers', 'representative_name' => 'Christa', 'representative_email' => 'Christa@rpm.co.za', 'representative_contact_1' => '0730264687', 'representative_contact_2' => ''],
    ['name' => 'RS Components', 'representative_name' => 'Given', 'representative_email' => 'RWebsiteZA@rs-components.com', 'representative_contact_1' => '0116919300', 'representative_contact_2' => ''],
    ['name' => 'Sareltech', 'representative_name' => 'Sarel', 'representative_email' => 'sarel@sareltech.com ', 'representative_contact_1' => '0832299497', 'representative_contact_2' => '0215529764'],
    ['name' => 'Sareltech', 'representative_name' => 'Elaine', 'representative_email' => 'admin@sareltech.com', 'representative_contact_1' => '0303908371', 'representative_contact_2' => '0215529764'],
    ['name' => 'Sareltech', 'representative_name' => 'Leon', 'representative_email' => 'leon@sareltech.com', 'representative_contact_1' => '0716727949', 'representative_contact_2' => '0215529764'],
    ['name' => 'SA Transmission', 'representative_name' => 'Ryan', 'representative_email' => 'satbsupplies@gmail.com', 'representative_contact_1' => '0218423780', 'representative_contact_2' => ''],
    ['name' => 'Savati', 'representative_name' => 'Graeme', 'representative_email' => 'graeme@savati.co.za', 'representative_contact_1' => '0215316646', 'representative_contact_2' => ''],
    ['name' => 'Schuurman', 'representative_name' => 'Marvin', 'representative_email' => 'marvin@sl.co.za', 'representative_contact_1' => '0219517733', 'representative_contact_2' => ''],
    ['name' => 'Schuurman Express', 'representative_name' => 'Dean', 'representative_email' => 'express@sl.co.za', 'representative_contact_1' => '0219517733', 'representative_contact_2' => ''],
    ['name' => 'Schuurman Tube', 'representative_name' => 'Nico', 'representative_email' => 'tube@sl.co.za', 'representative_contact_1' => '0219517733', 'representative_contact_2' => ''],
    ['name' => 'Servco', 'representative_name' => 'Gavin', 'representative_email' => 'gavin@servco.capetown', 'representative_contact_1' => '0219827484', 'representative_contact_2' => ''],
    ['name' => 'Sick', 'representative_name' => '', 'representative_email' => 'info@sickautomation.co.za', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'Sick', 'representative_name' => '', 'representative_email' => 'orders@sickautomation.co.za', 'representative_contact_1' => '', 'representative_contact_2' => ''],
    ['name' => 'SMC', 'representative_name' => 'Lorato', 'representative_email' => 'lmalepe@smcza.co.za', 'representative_contact_1' => '0826117770', 'representative_contact_2' => '0111005866'],
    ['name' => 'Springman', 'representative_name' => 'Dale', 'representative_email' => 'springman@iafrica.com', 'representative_contact_1' => '0219333622', 'representative_contact_2' => ''],
    ['name' => 'Stone Stamcor', 'representative_name' => 'Kevin', 'representative_email' => 'keving@stonestamcor.co.za', 'representative_contact_1' => '0114521499', 'representative_contact_2' => ''],
    ['name' => 'Technisales', 'representative_name' => 'Giovanni', 'representative_email' => 'conray@technisales.co.za', 'representative_contact_1' => '0215112202', 'representative_contact_2' => ''],
    ['name' => 'Technisales', 'representative_name' => 'Romeo', 'representative_email' => 'reece@technisales.co.za', 'representative_contact_1' => '0215112202', 'representative_contact_2' => ''],
    ['name' => 'Tectra', 'representative_name' => 'Allistar', 'representative_email' => 'allistar.appolis@boschrexroth.co.za', 'representative_contact_1' => '0215107802', 'representative_contact_2' => ''],
];
